import sys
import os
import urllib
import xbmc
import xbmcgui
import xbmcplugin
import xbmcaddon
import base64


from metahandler import metahandlers

addon = xbmcaddon.Addon()
home = xbmc.translatePath(addon.getAddonInfo('path'))
ddicon = xbmc.translatePath(os.path.join(home, 'icon.png'))
dialog = xbmcgui.Dialog()
addon_handle = int(sys.argv[1])
filminfo = addon.getSetting('enable_meta')


exec("import re;import base64");exec((lambda p,y:(lambda o,b,f:re.sub(o,b,f))(r"([0-9a-f]+)",lambda m:p(m,y),base64.b64decode("NGQgM2YoKToKCTQuMTYoMSwgJzMwJykKCgk0OSBhIDU0IDEyOgoJCTExIDFjIGFbJzEwJ10uNygnMWEnKToKCQkJCTVjID0gNDYuMjUuMjQoMjIsICcxOCcsIGFbJzEwJ10pCgkJMzU6CgkJCQk1ID0gYVsnNSddCgkJCQkxMSAxYyA1LjcoJzFhJyk6CgkJCQkJCTUgPSA0Ni4yNS4yNCgyMiwgJzE4JywgNSkKCQlmOiA1ID0gNDQJCQkJCgkJMjYgPSAyOC4yMyhhWyc5J10sIDFkPTVjKQoJCTExIDU6IDI2LjM0KHsnNSc6IDV9KQoJCTIwID0gNDAuMzdbMF0gKyAnP2E9JyArIDJkKGFbJzYzJ10pCgkJNC5jKDM4PTEsIDIwPTIwLCAyNz0yNiwgMjE9NDEpCgoJNC5kKDEpCgoKNGQgMmUoYSk6Cgk0LjE2KDEsICczMCcpCgk0OSAyIDU0IDJjWzJkKGEpXToKCQk1YyA9IDJbJzEwJ10KCQkzID0gMlsnMjAnXQoJCTExIDMuNygnNWYnKToKCQkJCTM1OiAzID0gNGIuM2QoMykKCQkJCWY6IDU1CgkJOSA9IDJbJzknXQoJCTE3ID0gMlsnMTcnXQoJCTE0ID0gMlsnMmInXQoJCTM1OiAxNSA9IDJbJzE1J10KCQlmOiAxNSA9ICcnCgkJMzU6IDEyID0gMlsnYSddCgkJZjogMTIgPSA0NAoJCTggPSBbXQoJCTYgPSAnJwoJCTFmID0gM2IKCQkxMSAxMjoKCQkJCTMgPSA0MC4zN1swXSArICc/YT0nICsgMmQoMTIpCgkJCQkxZiA9IDQxCgkJNTggMTQ6CgkJCQkzID0gKDQwLjM3WzBdICsKCQkJCSAiPzIwPSIgKyAyZi4xOSgzKSArCgkJCQkgIiZhPTJiIiArIAoJCQkJICImOT0iICsgMmYuMTkoOSkpCgkJMTEgNDUgPT0gJzVhJzoKCQkJCTU5ID0gMzIuNDIoMzM9J2InKQoJCQkJMTMgPSA1OS40MygnNGUnLCA5PTksIDE3PTE3LCAyOT0xNSkKCQkJCTVjID0gMTNbJzNlJ10KCQkJCTExIDVjID09ICcnOgoJCQkJCQk1YyA9IDJbJzEwJ10KCQkJCQkJMTEgMWMgNWMuNygnMWEnKToKCQkJCQkJCQk1YyA9IDQ2LjI1LjI0KDIyLCAnMTgnLCAyWycxMCddKQkJCQkJCgkJCQllID0gMTMKCQkJCTFlID0gMTNbJzI5J10KCQkJCTYgPSAxM1snMzYnXQoJCQkJMTEgMWMgMWUgPT0gJycgNWUgNiA9PSAnJzogNiA9ICcxYTovLzQ3LjViLzE1LzVkLycrMWUrJy42MCcKCQk1NjoKCQkJCTkgPSAiJTYyICglNjIpIiAlICg5LCAxNykKCQkJCWUgPSB7ICI1MSI6IDkgfQoJCQkJNiA9ICcnCgkJCQkxMSAxYyA1Yy43KCcxYScpOgoJCQkJCQk1YyA9IDQ2LjI1LjI0KDIyLCAnMTgnLCAyWycxMCddKQoJCTI2ID0gMjguMjMoOSwgMmE9NWMsIDFkPTVjKQoJCTI2LjQ4KDU3PSI1MCIsIDNhPSBlKQoJCTguNGMoKCc0ZiAzOScsICc1Mi40YSg1MyknKSkKCQkyNi4xYig4LCAzMT0zYikKCQkxMSAxYyA2ID09ICcnOiAyNi4zNCh7JzUnOiA2fSkKCQk0LmMoMzg9MSwgMjA9MywgMjc9MjYsIDNjPTYxKDJjWzJkKGEpXSksIDIxPTFmKQoKCTQuZCgxKQ==")))(lambda a,b:b[int("0x"+a.group(1),16)],"0|addon_handle|stream|videourl|xbmcplugin|fanart|backdrop|startswith|contextMenuItems|name|tag|f7f51775877e0bb6703520952b3c7840|addDirectoryItem|endOfDirectory|filmmeta|except|icon|if|tags|meta|blnresolve|imdb|setContent|year|logos|quote_plus|http|addContextMenuItems|not|iconImage|imdbid|folder|url|isFolder|home|ListItem|join|path|li|listitem|xbmcgui|imdb_id|thumbnailImage|resolve|streams|str|show_streams|urllib|movies|replaceItems|metahandlers|tmdb_api_key|setArt|try|backdrop_url|argv|handle|Information|infoLabels|False|totalItems|b64decode|cover_url|show_tags|sys|True|MetaData|get_meta|None|filminfo|os|films4u|setInfo|for|Action|base64|append|def|movie|Movie|Video|Title|XBMC|Info|in|pass|else|type|elif|mg|true|org|iconPath|bgs|and|aHR|jpg|len|s|id".split("|")))


exec("import re;import base64");exec((lambda p,y:(lambda o,b,f:re.sub(o,b,f))(r"([0-9a-f]+)",lambda m:p(m,y),base64.b64decode("MTIgMWUoMjEsIDIzKToKCTE3ICdjLjEzLjRmJyAzZCAxMC4xYSgnMjkuMjYnKToKCQk0NCA9IDFkCgkJMTcgJzE1JyAzZCAyMToKCQkJMmUgPSAyMS40KCI/NTQ9IilbLTFdLjQoIi8iKVstMV0uNCgiPyIpWzBdLjQoIiYiKVswXQoJCQk0NCA9ICdjOi8vYy4xMy4xNS8yZC8/MmY9JTQyJyAlIDJlCgkJMmI6CgkJCTNjIDgKCQkJNTI6IDQ0ID0gOC4zNSgyMSkKCQkJNDA6IDQ4CgkJMTcgNDQ6CgkJCWIgPSAxMC4xYygiZS40NiIpCgkJCTcgPSAzMy5lKDIzLCAyOD0iMWYuNTEiLCAxOT1iKQoJCQk3LjMyKCcxMycsIHsnNDUnOiAyM30pCgkJCTEwLjNlKCkuMmQoNDQsIDcpCgkJMmI6CgkJCTIyKCczOScsJzQ5IDRkIDM2JykKCgoxMiAyMig2PTFkLCAzYT0nJywgZj00Nyk6CgkxNyA2IDRkIDFkOiA2ID0gJzM5JwoJMTggPSAiMmMuMjAoJTQyLCU0MiwgJTQyLCAlNDIpIiAlICg2LCAzYSwgZiwgM2IpCgkxMC4xNigxOCkKCgoxMiAyNSgpOgogICIiIgogIDJhIDRlIDM3IDMwIDI0IDRjIDJjLgogICIiIgogIGEgPSBbXQogIDkgPSAzZi4zMVsyXQogIDE3IDExKDkpID49IDI6Cgk0YiA9IDNmLjMxWzJdCgk1ID0gNGIuMzQoJz8nLCAnJykKCTE3IDRiWzExKDRiKSAtIDFdID09ICcvJzoKCSAgNGIgPSA0YlswOjExKDRiKSAtIDJdCgkzID0gNS40KCcmJykKCWEgPSB7fQoJNTAgNTMgM2QgNDEoMTEoMykpOgoJICA0YSA9IHt9CgkgIDRhID0gM1s1M10uNCgnPScpCgkgIDE3ICgxMSg0YSkpID09IDI6CgkJYVs0YVswXV0gPSA0YVsxXQogIGQgYQoKCjEyIDFiKDI3KToKICAxMiAxNCgzOCk6CglkIDM4WzI3XS40MygpCgogIGQgMTQ=")))(lambda a,b:b[int("0x"+a.group(1),16)],"0|1|2|pairsofparams|split|cleanedparams|header|listitem|urlresolver|paramstring|param|iconimage|plugin|return|ListItem|duration|xbmc|len|def|video|_getter|youtube|executebuiltin|if|builtin|thumbnailImage|getInfoLabel|lower_getter|getInfoImage|None|resolve_play|DefaultVideo|Notification|url|notify|name|parameters|get_params|PluginName|field|iconImage|Container|Retrieves|else|XBMC|play|ytid|video_id|existing|argv|setInfo|xbmcgui|replace|resolve|offline|current|obj|AVP|msg|ddicon|import|in|Player|sys|except|range|s|lower|videourl|Title|Thumb|5000|pass|Link|splitparams|params|from|is|the|avp|for|png|try|i|v".split("|")))


tags = [
  {
    'name': 'Alien',
    'id': 'LiveTV',
    'icon': 'Alien.png',
	'fanart': 'alien4.png'
	
}, {
    'name': 'Predator',
    'id': 'Music',
    'icon': 'predator.png',
	'fanart': 'preda.png'
}, {
    'name': 'Extra  Footage',
    'id': 'extra',
    'icon': 'cast.png',
	'fanart': 'castw.png'
  }
]


exec("import re;import base64");exec((lambda p,y:(lambda o,b,f:re.sub(o,b,f))(r"([0-9a-f]+)",lambda m:p(m,y),base64.b64decode("MjkgPSBbewoJJzgnOiAnYyAxMicsCiAgJzknOiAnMjgnLAogICdlJzogJzExJysnMTknKycxYj09JywKICAnNic6ICcnLAogICcyJzogMTUsCiAgJzAnOiAxCn0sIHsKICAnOCc6ICdjIDMnLAogICc5JzogJzI3JywKICAnZSc6ICcxZScrJzE3JysnMWM9PScsCiAgJzYnOiAnJywKICAnMic6IDE1LAogICcwJzogMQp9LCB7CiAgJzgnOiAnYyAxMicsCiAgJzknOiAnMjgnLAogICdlJzogJzIwJysnMTAnKycyYj09JywKICAnNic6ICcnLAogICcyJzogMSwKICAnMCc6IDEKfSwgewogICc4JzogJ2MgMycsCiAgJzknOiAnMjcnLAogICdlJzogJ2YnKydhJysnNT09JywKICAnNic6ICcnLAogICcyJzogMSwKICAnMCc6IDEKfSwgewogICc4JzogJzIyJywKICAnOSc6ICcyYScsCiAgJ2UnOiAnMjQnKycxYScrJzE4PT0nLAogICc2JzogJycsCiAgJzInOiAxNSwKICAnMCc6IDEKfSwgewogICc4JzogJzFkJywKICAnOSc6ICcyNScsCiAgJ2UnOiAnMWYnKycxMycrJzIzPT0nLAogICc2JzogJycsCiAgJzInOiAxNSwKICAnMCc6IDEKfSwgewogICc4JzogJzFkJywKICAnOSc6ICcyNScsCiAgJ2UnOiAnZicrJ2QnKyc0PT0nLAogICc2JzogJycsCiAgJzInOiAxLAogICcwJzogMQp9LCB7CiAgJzgnOiAnYycsCiAgJzknOiAnMjYnLAogICdlJzogJzE0JysnNycrJ2I9PScsCiAgJzYnOiAnJywKICAnMic6IDEsCiAgJzAnOiAxCn0sIHsKICAnOCc6ICdjJywKICAnOSc6ICcyNicsCiAgJ2UnOiAnMTEnKycxNicrJzIxPT0nLAogICc2JzogJycsCiAgJzInOiAxNSwKICAnMCc6IDEKfV0=")))(lambda a,b:b[int("0x"+a.group(1),16)],"disabled|False|resolve|3|YXJ5L3BhcnRzLzE5NzYvMTMyNTE4NjQ5My9maWxlLm1rdg|L3BhcnRzLzE2MTYvMTMyNTE4NjY3Mi9maWxlLm1rdg|icon|Mi43ODozMjQwMC9saWJyYXJ5L3BhcnRzLzE5|name|year|jgzLjIyMi43ODozMjQwMC9saWJyYXJ5|NzcvMTMyNTE4NjM0MS9maWxlLm1rdg|Alien|jgzLjIyMi43ODozMjQwMC9saWJy|url|aHR0cDovLzgxL|gxLjgzLjIyMi43ODozMjQwMC9s|aHR0cDovL3Vw|Resurrection|VwdG9ib3guY29tL3l1YnczN|aHR0cDovLzgxLjgzLjIy|True|dG9ib3guY29tL21kZ3p6|wdG9ib3guY29tL21ucm|LzE4bWZtNmt6Z2xneA|dG9ib3guY29tL2cxe|3VwdG9ib3guY29t|HN2M2s4MzNyYg|9jb2E5ajU0YQ|Aliens|aHR0cDovL3V|aHR0cDovL3|aHR0cDovLz|NGp2NTk0aw|Prometheus|XdqODR2eg|aHR0cDovL|1986|1979|1992|1997|LiveTV|2012|aWJyYXJ5L3BhcnRzLzE5NzUvMTMyNTE4Njc4NC9maWxlLm1rdg".split("|")))





exec("import re;import base64");exec((lambda p,y:(lambda o,b,f:re.sub(o,b,f))(r"([0-9a-f]+)",lambda m:p(m,y),base64.b64decode("NzUgPSBbewoJJzQnOiAnMTUnLAoJJzUnOiAnMmYnLAoJJzgnOiAnZicrJzIyJysnM2Q9PScsCgknOGYnOiAnJywKCScxJzogNywKCScwJzogOGQKfSwgewoJJzQnOiAnNiAyJywKCSc1JzogJzVjJywKCSc4JzogJzExJysnMmMnKyczNj09JywKCSc4Zic6ICcnLAoJJzEnOiA3LAoJJzAnOiA4ZAp9LCB7CgknNCc6ICc2IDInLAoJJzUnOiAnNWMnLAoJJzgnOiAnMzAnKycxMicrJ2Q9PScsCgknOGYnOiAnJywKCScxJzogOGQsCgknMCc6IDhkCn0sIHsKCSc0JzogJzYnLAoJJzUnOiAnNWQnLAoJJzgnOiAnMjEnKycxZScrJzRiPT0nLAoJJzhmJzogJycsCgknMSc6IDcsCgknMCc6IDhkCn0sIHsKCSc0JzogJzYnLAoJJzUnOiAnNWQnLAoJJzgnOiAnNDInKycxNycrJ2E9PScsCgknOGYnOiAnJywKCScxJzogOGQsCgknMCc6IDhkCn0sIHsKCSc0JzogJzE1JywKCSc1JzogJzJmJywKCSc4JzogJzE5JysnYycrJzE4PT0nLAoJJzhmJzogJycsCgknMSc6IDhkLAoJJzAnOiA4ZAp9LCB7CgknNCc6ICc2IDc5IDgyJywKCSc1JzogJzdmJywKCSc4JzogJzExJysnM2EnKycyOD09JywKCSc4Zic6ICcnLAoJJzEnOiA3LAoJJzAnOiA4ZAp9LCB7CgknNCc6ICcxNiA1OCA2IDNiJywKCSc1JzogJzU3JywKCSc4JzogJ2YnKycxZCcrJzQ0PT0nLAoJJzhmJzogJycsCgknMSc6IDcsCgknMCc6IDhkCn0sIHsKCSc0JzogJzE2IDU4IDYgM2InLAoJJzUnOiAnNTcnLAoJJzgnOiAnMzUnKycxYicrJzk9PScsCgknOGYnOiAnJywKCScxJzogOGQsCgknMCc6IDhkCn0sIHsKCSc0JzogJzEwIDU4IDYnLAoJJzUnOiAnNTYnLAoJJzgnOiAnZScrJzQwJysnMmE9PScsCgknOGYnOiAnJywKCScxJzogNywKCScwJzogOGQKfSwgewoJJzQnOiAnMTAgNTggNicsCgknNSc6ICc1NicsCgknOCc6ICcyNScrJzFjJysnYicsCgknOGYnOiAnJywKCScxJzogOGQsCgknMCc6IDhkCn1dCgoKNzEgPSBbewoJJzQnOiAnMTQgMTAgNmQnLAoJJzUnOiAnODMnLAoJJzgnOiAnZScrJzI5JysnNDE9PScsCgknOGYnOiAnJywKCScxJzogNywKCScwJzogOGQKfSwgewoJJzQnOiAnMTAgMjcnLAoJJzUnOiAnNTUnLAoJJzgnOiAnMjEnKycyYicrJzMyPT0nLAoJJzhmJzogJycsCgknMSc6IDcsCgknMCc6IDhkCn0sIHsKCSc0JzogJzVmIDUzIDE0IDEzIDUyIDE2JywKCSc1JzogJzJlJywKCSc4JzogJzVlJysnM2UnKycxZj09JywKCSc4Zic6ICcnLAoJJzEnOiA3LAoJJzAnOiA4ZAp9LCB7CgknNCc6ICcxNCA2NCA3ZDogMTMgNTAnLAoJJzUnOiAnN2EnLAoJJzgnOiAnMTEnKycyMycrJzNmPT0nLAoJJzhmJzogJycsCgknMSc6IDcsCgknMCc6IDhkCn0sIHsKCSc0JzogJzE0IDEzIDUyIDEwIDMnLAoJJzUnOiAnMmUnLAoJJzgnOiAnM2MnKycyZCcrJzQzPT0nLAoJJzhmJzogJycsCgknMSc6IDcsCgknMCc6IDhkCn0sIHsKCSc0JzogJzg4IDdiIDcwIDhlIDg3IDgxIDdiOiAxNCAxMyA1MiA2JywKCSc1JzogJzU1JywKCSc4JzogJ2YnKycyNCcrJzM0PT0nLAoJJzhmJzogJzRjOi8vNjguNDguNDcvNzMvNjMvOGEvOGMvNWEuNTQ/OGI9NGUnLAoJJzEnOiA3LAoJJzAnOiA4ZAp9LCB7CgknNCc6ICcxNCA3MiA2OSAxNCAxMyA1MiAxMCcsCgknNSc6ICcyZScsCgknOCc6ICdmJysnNTEnKycxYT09JywKCSc4Zic6ICcnLAoJJzEnOiA3LAoJJzAnOiA4ZAp9LCB7CgknNCc6ICcxNiA4OSA2ZSA1OTogMTQgODUgNzcgNGQnLAoJJzUnOiAnMmUnLAoJJzgnOiAnZScrJzMzJysnMzE9PScsCgknOGYnOiAnNjA6Ly84Ni40OS40Ny82YS83Yy82Ny81Yi41NCcsCgknMSc6IDcsCgknMCc6IDhkCn0sIHsKCSc0JzogJzE0IDEwIDgwICcsCgknNSc6ICc3ZScsCgknOCc6ICczOCcrJzM3JysnMzk9PScsCgknOGYnOiAnJywKCScxJzogNywKCScwJzogOGQKfSwgewoJJzQnOiAnMjcgNTIgNmUgNjE6IDE1IDY1JywKCSc1JzogJzJmJywKCSc4JzogJzRjOi8vNjguNjIuNDcvNzY/OGI9NGEnLAoJJzhmJzogJzYwOi8vNDUtODQuNGYuNDcvNDUvNjYsNmYsNzgvNDYvMjAvMjYtNmItNzQtMjYtMmYtNmMuNTQnLAoJJzEnOiA3LAoJJzAnOiA4ZAp9XQ==")))(lambda a,b:b[int("0x"+a.group(1),16)],"disabled|resolve|2|3|name|year|Predator|True|url|aWJyYXJ5L3BhcnRzLzE5NTYvMTM1NDA3MDY5OC9maWxlLm1rdg|WJyYXJ5L3BhcnRzLzE3MjUvMTI5OTU4OTc1NS9maWxlLm1rdg|cmFyeS9wYXJ0cy8xOTQ1MC8xNDIwNTU3OTI0L2ZpbGUubXA0|3ODozMjQwMC9saWJyYXJ5L3BhcnRzLzE3MjMvMT|cnRzLzE3MjQvMTM1MTc2NjY1OS9maWxlLm1rdg|aHR0cDovL3Vw|aHR0cDovL|Alien|aHR0cDovL3V|LjIyMi43ODozMjQwMC9saWJyYXJ5L3Bh|Making|The|Predators|Aliens|jgzLjIyMi43ODozMjQwMC9sa|M0OTAxNTg2Mi9maWxlLm1rdg|aHR0cDovLzgxLjgzLjIyMi4|uY29tL282bmNjaDhhazY5MQ|gzLjIyMi43ODozMjQwMC9s|E1OC4yMjg6MzI0MDAvbGli|3VwdG9ib3guY29tL3pibj|VwdG9ib3guY29tL2I0NW5|29tL2toNTBxdnZ2cXFiag|w8kdqnupdkalmvghkuo2|aHR0cDovL3|3VwdG9ib3guY29tLzlub|wdG9ib3guY29tL3N1Z|3VwdG9ib3guY29tLzk|aHR0cDovLzg3LjY2Lj|predators|Evolution|29qamZ2cDdyM256Yg|dG9ib3guY29tL3lyO|zBiOGUwdmxhY3JiYw|VwdG9ib3guY29tL2R|wdG9ib3guY29tLzM5|G9ib3guY29tLzFme|2003|2010|aHR0cDovLzgxLjgz|vZHJibmpuZGJmeg|5emp1Z2V5N2xpbA|dG9ib3guY29tL3F|xeWp1cm5nd29zYQ|aHR0cDovLzgxLj|Zzdpd2JidWlodw|9ib3guY29tL2Q5|aHR0cDovL3VwdG|Zmh1bG1yZW0xdA|wdG9ib3guY29tL|Requiem|aHR0cDovL3Vwd|DBzNDB5d3NoZQ|L3VwdG9ib3guY|mtuemxzNHNoaw|dG9ib3guY29tL|Tc1dG41NHZ0ZQ|aHR0cDovLzgxL|nU3aDEzcWh5cA|hybDVqY2xhYw|images|t_mp_quality|com|cinematerial|photobucket|sgFuSotBdNI|2eHFyMGlzYw|https|Collection|1456814724|moviepilot|Prometheus|3VwdG9ib3g|of|Firepower|jpg|2001|2004|2007|vs|Basement|qmawucla|IMG_9080|1990|1987|aHR0cDov|Superior|http|Species|youtube|posters|Furious|Reborn|c_fill|dmpsk8|www|Within|albums|sequel|374942|Legacy|the|h_1077|Bleeds|extra|Beast|media|since|Music|watch|Burns|w_742|Dark|2012|It|v635|Gods|2002|2015|Saga|Kill|Ages|1999|cdn|Bob|img|Can|If|in|md|v|qm|False|We|icon".split("|")))



streams = {
  'LiveTV': sorted((i for i in LiveTV if not i.get('disabled', False)), key=lower_getter('name')),
  'Music': sorted((i for i in Music if not i.get('disabled', False)), key=lower_getter('name')),
  'extra': sorted((i for i in extra if not i.get('disabled', False)), key=lower_getter('name')),
  # 'LiveTV': sorted(LiveTV, key=lower_getter('name')),
  # 'Movies': sorted(Movies, key=lower_getter('name')),
}


PARAMS = get_params()
TAG = None
NAME = None
URL = None


try:
  TAG = PARAMS['tag']
except:
  pass
try: URL = urllib.unquote_plus(PARAMS["url"])
except: pass
try: NAME = urllib.unquote_plus(PARAMS["name"])
except: pass


if TAG == None:
  show_tags()
elif TAG == 'resolve':
  resolve_play(URL, NAME)
else:
  show_streams(TAG)
