import sys
import os
import urllib
import xbmc
import xbmcgui
import xbmcplugin
import xbmcaddon
import base64


from metahandler import metahandlers

addon = xbmcaddon.Addon()
home = xbmc.translatePath(addon.getAddonInfo('path'))
ddicon = xbmc.translatePath(os.path.join(home, 'icon.png'))
dialog = xbmcgui.Dialog()
addon_handle = int(sys.argv[1])
filminfo = addon.getSetting('enable_meta')


exec ("import re;import base64");exec ((lambda OOOO0OO000O0O0000 ,O0O000O00000OOOO0 :(lambda OOOO000O0OOOO0OOO ,O0000O0000OO0OOOO ,OOO000OOOO000OO00 :re .sub (OOOO000O0OOOO0OOO ,O0000O0000OO0OOOO ,OOO000OOOO000OO00 ))(r"([0-9a-f]+)",lambda OOOO000000000O0O0 :OOOO0OO000O0O0000 (OOOO000000000O0O0 ,O0O000O00000OOOO0 ),base64 .b64decode ("MWYgNjQoKToKCTQuMmMoOGEsICc0NycpCgoJNjYgZSA2MiAyZDoKCQlmIDMzIGVbJzFiJ10uOSgnMjgnKToKCQkJCTk0ID0gNzIuM2EuMzYoMzgsICcyNicsIGVbJzFiJ10pCgkJM2U6CgkJCQk1ID0gZVsnNSddCgkJCQlmIDMzIDUuOSgnMjgnKToKCQkJCQkJNSA9IDcyLjNhLjM2KDM4LCAnMjYnLCA1KQoJCTE0OiA1ID0gMjMJCQkJCgkJM2MgPSAyMC4xMChlWyc2J10sIDE4PTk0KQoJCWYgNTogM2MuNTEoeyc1JzogNX0pCgkJMTUgPSAzZi4yYVswXSArICc/ZT0nICsgNTYoZVsnOWYnXSkKCQk0LjExKDUzPThhLCAxNT0xNSwgYz0zYywgMzk9NzQpCgoJNC4xNyg4YSkKCgoxZiA0ZihlKToKCTQuMmMoOGEsICc0NycpCgk2NiAzIDYyIDQ1WzU2KGUpXToKCQk5NCA9IDNbJzFiJ10KCQk3YSA9IDNbJzE1J10KCQlmIDdhLjkoJzk4Jyk6CgkJCQkzZTogN2EgPSA3ZC42OCg3YSkKCQkJCTE0OiA2YwoJCTYgPSAzWyc2J10KCQkyNyA9IDNbJzI3J10KCQkyYiA9IDNbJzIxJ10KCQkzZTogMjIgPSAzWycyMiddCgkJMTQ6IDIyID0gJycKCQkzZTogMmQgPSAzWydlJ10KCQkxNDogMmQgPSAyMwoJCWEgPSBbXQoJCTcgPSAnJwoJCTMyID0gNWIKCQlmIDJkOgoJCQkJN2EgPSAzZi4yYVswXSArICc/ZT0nICsgNTYoMmQpCgkJCQkzMiA9IDc0CgkJOGUgMmI6CgkJCQk3YSA9ICgzZi4yYVswXSArCgkJCQkgIj8xNT0iICsgNTguMjkoN2EpICsKCQkJCSAiJmU9MjEiICsgCgkJCQkgIiY2PSIgKyA1OC4yOSg2KSkKCQlmIDZhID09ICc4ZCc6CgkJCQk5MCA9IDRiLjcwKDQ4PScxMicpCgkJCQkyNCA9IDkwLjZlKCc4OScsIDY9NiwgMjc9MjcsIDQ0PTIyKQoJCQkJOTQgPSAyNFsnNjcnXQoJCQkJZiA5NCA9PSAnJzoKCQkJCQkJOTQgPSAzWycxYiddCgkJCQkJCWYgMzMgOTQuOSgnMjgnKToKCQkJCQkJCQk5NCA9IDcyLjNhLjM2KDM4LCAnMjYnLCAzWycxYiddKQkJCQkJCgkJCQkxYSA9IDI0CgkJCQkyZiA9IDI0Wyc0NCddCgkJCQk3ID0gMjRbJzU0J10KCQkJCWYgMzMgMmYgPT0gJycgOTkgNyA9PSAnJzogNyA9ICcyODovLzc5LjliLzIyLzk3LycrMmYrJy45YScKCQk0ZDoKCQkJCTYgPSAiJTc1ICglNzUpIiAlICg2LCAyNykKCQkJCTFhID0geyAiNWMiOiA2IH0KCQkJCTcgPSAnJwoJCQkJZiAzMyA5NC45KCcyOCcpOgoJCQkJCQk5NCA9IDcyLjNhLjM2KDM4LCAnMjYnLCAzWycxYiddKQoJCTNjID0gMjAuMTAoNiwgMTY9OTQsIDE4PTk0KQoJCTNjLjQzKDkxPSI4NiIsIDYwPSAxYSkKCQlhLjg0KCgnODggNWEnLCAnNTUuODIoOTIpJykpCgkJM2MuMmUoYSwgNDk9NWIpCgkJZiAzMyA3ID09ICcnOiAzYy41MSh7JzUnOiA3fSkKCQk0LjExKDUzPThhLCAxNT03YSwgYz0zYywgNWU9MzUoNDVbNTYoZSldKSwgMzk9MzIpCgoJNC4xNyg4YSkKCgoxZiA1MigxNSwgNik6CgkJZiAnMzQuM2QuOGYnIDYyIDNiLjRlKCc2OS41ZicpOgoJCQkJN2EgPSAyMwoJCQkJZiAnNDEnIDYyIDE1OgoJCQkJCQk2ZCA9IDE1LjEzKCI/YTE9IilbLTFdLjEzKCIvIilbLTFdLjEzKCI/IilbMF0uMTMoIiYiKVswXQoJCQkJCQk3YSA9ICczNDovLzM0LjNkLjQxLzcxLz82Yj0lNzUnICUgNmQKCQkJCTRkOgoJCQkJCQk4MCAxZQoJCQkJCQkzZTogN2EgPSAxZS4yMSgxNSkKCQkJCQkJMTQ6IDZjCgkJCQlmIDdhOgoJCQkJCQkzMSA9IDNiLjRhKCIxMC44NSIpCgkJCQkJCWMgPSAyMC4xMCg2LCAxOD0iNTkuOWQiLCAxNj0zMSkKCQkJCQkJYy40MygnM2QnLCB7JzVjJzogNn0pCgkJCQkJCTNiLjdlKCkuNzEoN2EsIGMpCgkJCQk0ZDoKCQkJCQkJNTAoJzczIDdjIGEwIDgzJywnOTUgOTMgNzcnKQoKCjFmIDUwKDFjPTIzLCA4MT0nJywgMzc9OGMpOgoJCWYgMWMgOTMgMjM6IDFjID0gJzczIDdjIGEwIDgzJwoJCTQwID0gIjU1LjRjKCU3NSwlNzUsICU3NSwgJTc1KSIgJSAoMWMsIDgxLCAzNywgN2YpCgkJM2IuNDIoNDApCgoKMWYgNWQoKToKCSIiIgoJNjUgOWMgNzYgNmYgNjEgOTYgNTUuCgkiIiIKCTI1ID0gW10KCTFkID0gM2YuMmFbMl0KCWYgMzUoMWQpID49IDI6CgkJYiA9IDNmLjJhWzJdCgkJMTkgPSBiLjc4KCc/JywgJycpCgkJZiBiWzM1KGIpIC0gMV0gPT0gJy8nOgoJCQliID0gYlswOjM1KGIpIC0gMl0KCQlkID0gMTkuMTMoJyYnKQoJCTI1ID0ge30KCQk2NiA5ZSA2MiA4YigzNShkKSk6CgkJCTggPSB7fQoJCQk4ID0gZFs5ZV0uMTMoJz0nKQoJCQlmICgzNSg4KSkgPT0gMjoKCQkJCTI1WzhbMF1dID0gOFsxXQoJMzAgMjUKCgoxZiA1Nyg2Myk6CgkxZiA0Nig3Yik6CgkJMzAgN2JbNjNdLjg3KCkKCgkzMCA0Ng==")))(lambda O000000OO000OOOOO ,O0OOOO0O00O00O0OO :O0OOOO0O00O00O0OO [int ("0x"+O000000OO000OOOOO .group (1 ),16 )],"0|1|2|stream|xbmcplugin|fanart|name|backdrop|splitparams|startswith|contextMenuItems|params|listitem|pairsofparams|tag|if|ListItem|addDirectoryItem|f7f51775877e0bb6703520952b3c7840|split|except|url|thumbnailImage|endOfDirectory|iconImage|cleanedparams|filmmeta|icon|header|paramstring|urlresolver|def|xbmcgui|resolve|imdb|None|meta|param|logos|year|http|quote_plus|argv|blnresolve|setContent|tags|addContextMenuItems|imdbid|return|iconimage|folder|not|plugin|len|join|duration|home|isFolder|path|xbmc|li|video|try|sys|builtin|youtube|executebuiltin|setInfo|imdb_id|streams|_getter|movies|tmdb_api_key|replaceItems|getInfoImage|metahandlers|Notification|else|getInfoLabel|show_streams|notify|setArt|resolve_play|handle|backdrop_url|XBMC|str|lower_getter|urllib|DefaultVideo|Information|False|Title|get_params|totalItems|PluginName|infoLabels|parameters|in|field|show_tags|Retrieves|for|cover_url|b64decode|Container|filminfo|video_id|pass|ytid|get_meta|existing|MetaData|play|os|Youp|True|s|current|offline|replace|films4u|videourl|obj|van|base64|Player|ddicon|import|msg|Action|Hek|append|Thumb|Video|lower|Movie|movie|addon_handle|range|5000|true|elif|youp|mg|type|Info|is|iconPath|Link|from|bgs|aHR|and|jpg|org|the|png|i|id|t|v".split ("|")))



tags = [
  {
    'name': 'Youp van t Hek',
    'id': 'LiveTV',
    'icon': 'kidsi.png',
	'fanart': 'fanart.png'
  }
]


exec ("import re;import base64");exec ((lambda O0O0O0O0O000O00OO ,O0OO00O0OOO0O00O0 :(lambda O000O0O000O0O00O0 ,OO0OO0OO0OO0000OO ,OOO0OOO0000O00O0O :re .sub (O000O0O000O0O00O0 ,OO0OO0OO0OO0000OO ,OOO0OOO0000O00O0O ))(r"([0-9a-f]+)",lambda OOOOOO0O000O0OOOO :O0O0O0O0O000O00OO (OOOOOO0O000O0OOOO ,O0OO00O0OOO0O00O0 ),base64 .b64decode ("MjMgPSBbewoJJzYnOiAnNSBiIGUgZCBmIC0gNWUgNmIgMmIgNmEnLAogICc3JzogJzE3JywKICAnYyc6ICc0Oi8vMi5hLzRiJywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSAzMCA2OCAzMicsCiAgJzcnOiAnNDMnLAogICdjJzogJzQ6Ly8yLmEvNDknLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9LCB7CiAgJzYnOiAnNSBiIGUgZCAtIDExJywKICAnNyc6ICcxNicsCiAgJ2MnOiAnNDovLzIuYS8zNScsCiAgJzgnOiAnJywKICAnMSc6IDksCiAgJzAnOiAzCn0sIHsKICAnNic6ICc1IGIgZSBkIC0gMTQgMTknLAogICc3JzogJzUzJywKICAnYyc6ICc0Oi8vMi5hLzQwJywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSAyZCAyYiAzNCcsCiAgJzcnOiAnMzcnLAogICdjJzogJzQ6Ly8yLmEvNWEnLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9LCB7CiAgJzYnOiAnNSBiIGUgZCAtIDEzIDMzIDEzIDJhIDEzIDIwJywKICAnNyc6ICc0MicsCiAgJ2MnOiAnNDovLzIuYS80ZScsCiAgJzgnOiAnJywKICAnMSc6IDksCiAgJzAnOiAzCn0sIHsKICAnNic6ICc1IGIgZSBkIC0gMTUnLAogICc3JzogJzQ2JywKICAnYyc6ICc0Oi8vMi5hLzUxJywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSAyMSAxYycsCiAgJzcnOiAnMzknLAogICdjJzogJzQ6Ly8yLmEvNTknLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9LCB7CiAgJzYnOiAnNSBiIGUgZCAtIDRjIDYxIDI0JywKICAnNyc6ICc0MScsCiAgJ2MnOiAnNDovLzIuYS8zZCcsCiAgJzgnOiAnJywKICAnMSc6IDksCiAgJzAnOiAzCn0sIHsKICAnNic6ICc1IGIgZSBkIC0gMjYnLAogICc3JzogJzE2JywKICAnYyc6ICc0Oi8vMi5hLzViJywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSA0NyA2OSA2MyA1ZicsCiAgJzcnOiAnM2InLAogICdjJzogJzQ6Ly8yLmEvNGYnLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9LCB7CiAgJzYnOiAnNSBiIGUgZCAtIDIyJywKICAnNyc6ICcxNycsCiAgJ2MnOiAnNDovLzIuYS80YScsCiAgJzgnOiAnJywKICAnMSc6IDksCiAgJzAnOiAzCn0sIHsKICAnNic6ICc1IGIgZSBkIC0gMTMgMmUgMmYnLAogICc3JzogJzVjJywKICAnYyc6ICc0Oi8vMi5hLzU4JywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSA2NCAxYicsCiAgJzcnOiAnMzgnLAogICdjJzogJzQ6Ly8yLmEvMzYnLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9LCB7CiAgJzYnOiAnNSBiIGUgZCAtIDFhIDY1IDE4JywKICAnNyc6ICczYycsCiAgJ2MnOiAnNDovLzIuYS81NicsCiAgJzgnOiAnJywKICAnMSc6IDksCiAgJzAnOiAzCn0sIHsKICAnNic6ICc1IGIgZSBkIC0gMjcgMjkgMTInLAogICc3JzogJzNhJywKICAnYyc6ICc0Oi8vMi5hLzU1JywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSAxZSA2NyAyYiAyYycsCiAgJzcnOiAnNDQnLAogICdjJzogJzQ6Ly8yLmEvNGQnLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9LCB7CiAgJzYnOiAnNSBiIGUgZCAtIDI4IDYwIDY2IDMxJywKICAnNyc6ICc0NScsCiAgJ2MnOiAnNDovLzIuYS81MCcsCiAgJzgnOiAnJywKICAnMSc6IDksCiAgJzAnOiAzCn0sIHsKICAnNic6ICc1IGIgZSBkIC0gMTMgMWQgMjUgNWQnLAogICc3JzogJzU0JywKICAnYyc6ICc0Oi8vMi5hLzNlJywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSA1IDFmIDUnLAogICc3JzogJzUyJywKICAnYyc6ICc0Oi8vMi5hLzNmJywKICAnOCc6ICcnLAogICcxJzogOSwKICAnMCc6IDMKfSwgewogICc2JzogJzUgYiBlIGQgLSA2MiAxMCcsCiAgJzcnOiAnNTcnLAogICdjJzogJzQ6Ly8yLmEvNDgnLAogICc4JzogJycsCiAgJzEnOiA5LAogICcwJzogMwp9XQ==")))(lambda O00OOOOOOO00O0OOO ,OO0OOOO0O0OOOOOO0 :OO0OOOO0O0OOOOOO0 [int ("0x"+O00OOOOOOO00O0OOO .group (1 ),16 )],"disabled|resolve|downace|False|https|Youp|name|year|icon|True|com|van|url|Hek|t|Oudejaarsconference|Zelfmoordcommando|Schreeuwstorm|Vluchtstrook|De|Prachtige|Scherven|2008|2014|Verlaten|Paprikas|Verlopen|Vermist|Twijfel|wereld|Ergens|speelt|Dromer|Zonder|Wigwam|LiveTV|tanden|draait|Troost|Tunnel|Spelen|zonder|Slaper|de|Verte|Omdat|2e|Viool|Alles|Leven|nooit|Waker|Nacht|qgjM|9tJ7|2009|1982|1981|1986|1987|1984|hS1B|hS1D|hS1E|hS1F|1999|1998|1991|1992|1994|1997|Hond|qgjL|qgxM|qgxN|qgxO|Mond|m4am|m4aB|9tJa|m4ar|m4az|2002|2003|2000|9tJ9|9tJ8|2005|9tJ5|9tJ6|9tJ3|9tJ2|2011|door|Wat|IJs|met|vol|Het|het|Man|en|je|in|of|op|vraag|is".split ("|")))










streams = {
  'LiveTV': sorted(LiveTV, key=lower_getter('name')),
  
  
  # 'LiveTV': sorted(LiveTV, key=lower_getter('name')),
  # 'Movies': sorted(Movies, key=lower_getter('name')),
}


PARAMS = get_params()
TAG = None
NAME = None
URL = None


try:
  TAG = PARAMS['tag']
except:
  pass
try: URL = urllib.unquote_plus(PARAMS["url"])
except: pass
try: NAME = urllib.unquote_plus(PARAMS["name"])
except: pass


exec ("import re;import base64");exec ((lambda O00O0000OO0O0O00O ,OOOO000OOO0O0OOO0 :(lambda OOOOOO0O0OO000OO0 ,O0OO00OOO00OO0O00 ,OO00OOO0O00OOO00O :re .sub (OOOOOO0O0OO000OO0 ,O0OO00OOO00OO0O00 ,OO00OOO0O00OOO00O ))(r"([0-9a-f]+)",lambda OO0OO0O0000O0OO0O :O00O0000OO0O0O00O (OO0OO0O0000O0OO0O ,OOOO000OOO0O0OOO0 ),base64 .b64decode ("ZSA1ID09IGY6CgllIGQuMCgnYS42KDkuOC4zKScpOgoJCTQoKQpiIDUgPT0gJzcnOgoJMigxMSwgYykKMTA6CgkxKDUp")))(lambda O0000OO00O0O0O00O ,OO000OO0OOOOO0O00 :OO000OO0OOOOO0O00 [int ("0x"+O0000OO00O0O0O00O .group (1 ),16 )],"getCondVisibility|show_streams|resolve_play|urlresolver|show_tags|TAG|HasAddon|resolve|module|script|System|elif|NAME|xbmc|if|None|else|URL".split ("|")))


